imx6ul-var-dart: fix errors
- iw612_utils: fix ot installation error disabling it. Aligned with Yocto
- flex-builder: add installation of zImage and kernel dtbs
- add wl18xx_firmware.mk

The scope of this patch is only to backup

Signed-off-by: FrancescoFerraro <francesco.f@variscite.com>

diff --git a/tools/create_bootpartition b/tools/create_bootpartition
--- a/tools/create_bootpartition
+++ b/tools/create_bootpartition
@@ -46,16 +46,18 @@ generate_bootpartition() {
     # install /lib/firmware
     mkdir -p $bootpartdir/firmware
     if [ $SOCFAMILY = IMX ]; then
+	[ ! -d $FBOUTDIR/bsp/imx_firmware/lib/firmware/imx/easrc ] && bld imx_firmware -a $DESTARCH -p $SOCFAMILY
 	[ ! -d $FBOUTDIR/bsp/brcm_firmware/lib/firmware ] && bld brcm_firmware -a $DESTARCH -p $SOCFAMILY
+	[ ! -d $FBOUTDIR/bsp/wl18xx_firmware/lib/firmware ] && bld wl18xx_firmware -a $DESTARCH -p $SOCFAMILY
 
     [ -d $FBOUTDIR/bsp/imx_firmware/lib/firmware ] && \
         cp -Prf $FBOUTDIR/bsp/imx_firmware/lib/firmware/* $bootpartdir/firmware || echo "Directory not found: $FBOUTDIR/bsp/imx_firmware/lib/firmware"
-    [ -d "$FBOUTDIR/bsp/imx_mcore_demos/imx93-m33-demo" ] && \
-        cp -Prf "$FBOUTDIR/bsp/imx_mcore_demos/imx93-m33-demo/imx93-"*m33*.elf "$DESTDIR/usr/lib/ethosu_firmware" "$bootpartdir/firmware" || echo "Directory not found: $FBOUTDIR/bsp/imx_mcore_demos/imx93-m33-demo"
     [ -d $FBOUTDIR/bsp/brcm_firmware/lib/firmware ] && \
         cp -Prf $FBOUTDIR/bsp/brcm_firmware/lib/firmware/* $bootpartdir/firmware || echo "Directory not found: $FBOUTDIR/bsp/brcm_firmware/lib/firmware"
     [ -d $FBOUTDIR/bsp/iw612_firmware/lib/firmware/nxp ] && \
         cp -Prf $FBOUTDIR/bsp/iw612_firmware/lib/firmware/* $bootpartdir/firmware || echo "Directory not found: $FBOUTDIR/bsp/iw612_firmware/lib/firmware"
+    [ -d $FBOUTDIR/bsp/wl18xx_firmware/lib/firmware/ti-connectivity ] && \
+        cp -Prf $FBOUTDIR/bsp/wl18xx_firmware/lib/firmware/* $bootpartdir/firmware || echo "Directory not found: $FBOUTDIR/bsp/wl18xx_firmware/lib/firmware"
     fi
 
     # install distro boot script
